CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 멤버 넘버 시퀀스

CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시판 번호 시퀀스

CREATE SEQUENCE SEQ_REPLY_NO NOCACHE; -- 댓글 번호 시퀀스

CREATE SEQUENCE SEQ_BOARD_IMG_NO NOCACHE; -- 게시판 이미지 번호 시퀀스

CREATE SEQUENCE SEQ_PETSITTER_NO NOCACHE; -- 펫시터 번호 시퀀스

CREATE SEQUENCE SEQ_RS_NO NOCACHE; -- 예약 번호 시퀀스

CREATE SEQUENCE SEQ_PET_NO NOCACHE; -- 반려견 번호 시퀀스

CREATE SEQUENCE SEQ_APPLICATION_NO NOCACHE; -- 신청 번호 시퀀스

CREATE SEQUENCE SEQ_AUTH_KEY_NO NOCACHE; -- 이메일 인증 번호 시퀀스 

CREATE SEQUENCE SEQ_MESSAGE_NO NOCACHE; -- 메세지 번호 시퀀스

CREATE SEQUENCE SEQ_LIVE_NO NOCACHE; -- 라이브 카드 번호 시퀀스

CREATE SEQUENCE SEQ_LIVE_IMG_NO NOCACHE; -- 라이브 카드 이미지번호 시퀀스

CREATE SEQUENCE SEQ_PAY_NO NOCACHE; -- 결제 번호 시퀀스

CREATE SEQUENCE SEQ_CHATTING_MESSAGE_NO NOCACHE; -- 채팅메세지번호 시퀀스

CREATE SEQUENCE SEQ_CHATTING_ROOM_NO NOCACHE; -- 채팅방번호 시퀀스

CREATE SEQUENCE SEQ_REPORT_NO NOCACHE; -- 신고번호 시퀀스

COMMIT;

